server:
  port: 9393
  
resilience4j:
  circuitbreaker:
    instances:
      myservice:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 2
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 2
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 5
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED
        
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
        
        