FROM openjdk:17-alpine
WORKDIR usr/src
ADD /target/authorizeapp-0.0.1-SNAPSHOT.jar /usr/src/authorizeapp-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","authorizeapp-0.0.1-SNAPSHOT.jar"]
ENV MYSQLURL=jdbc:mysql://mysqls:3306/ctssigndb?createDatabaseIfNotExist=true&user=root&password=password