#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/ctspassengerdb?createDatabaseIfNotExist=true&user=root&password=password

#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update


server:
  port: 9192
  
app:
  message: Successfuly sent the book detail to recommendation service
  
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ctsshopping?createDatabaseIfNotExist=true&user=root&password=password
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    exchange: ctsshopexchange
    queue: ctsqueue
    routingkey: ctsshopkey
    